sudo: false

language: java

jdk:
  - oraclejdk8
  - openjdk8

os:
  - linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: ./gradlew --version

script: ./gradlew build --refresh-dependencies --no-daemon --continue

after_success:
  - ./ci/deploy_snapshot.sh
